# Generated by Django 5.1.7 on 2025-04-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="student",
            table="users",
        ),
    ]
