# Generated by Django 5.1.7 on 2025-04-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="f_name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="employee",
            old_name="l_name",
            new_name="last_name",
        ),
    ]
