# Generated by Django 5.1.7 on 2025-04-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_alter_book_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="book",
            table=None,
        ),
    ]
